# https://render.com/docs/blueprint-spec
services:
  - type: web
    name: url-to-pdf
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
